server:
  port: ${PORT:8080}

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:127.0.0.1}:3306/${DB:fastwebsite}?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: ${DB_USER:root}
    password: ${DB_PWD:123456}
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "*.gif,*.png,*.jpg,*.html,*.js,*.css,*.ico,/druid/*"
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: true
        login-username: admin
        login-password: ${DRUID_PWD:fastjava@2018}
      filter:
        slf4j:
          enabled: true
          statement-log-enabled: false
          connection-log-enabled: false
          result-set-log-enabled: true
          statement-executable-sql-log-enable: true

logging:
  config: classpath:config/log4j2.xml

mybatis:
  config-location: classpath:config/mybatis.xml
  mapper-locations: classpath:sqlMapper/*.xml

fastjava:
  options-auhority: true
  exception:
    message: "系统异常，请稍后再试！"
    response-ok: true
    prompt-stack: true

quartz:
  start-delayed: 10
  log-enabled: true
  jobs: